### ISSUE TITLE
A few warnings running qtheme.sh

### ISSUE THREAD

**Issue by q4osteam** [seb3773/Q4OSseb#15]
See the log attached 
[qtheme.log](https://github.com/seb3773/Q4OSseb/files/13697532/qtheme.log)

**Comment by seb3773** [comment]
Strangely, I can't reproduce it on my current config, need to try it on another computer or a vm. I upload a new version with a modification for this, can you tell me if the error persist ?

**Comment by q4osteam** [comment]
Last update didn't solve the issue, log file keeps the same error messages.
Default Q4OS installation with basic profile applied in Vrtualbox.

**Comment by seb3773** [comment]
I uploaded a correction, hope it's ok now (seems to be an error if tar want to restore nonexistent user id on the system; I applied --owner root --group root --no-same-owner to the tar command) although didn't have a chance to test on a fresh install yet,...
Maybe the desktop doesn't respond properly because of this problem ? Please tell me :)

**Comment by q4osteam** [comment]
The latest update solved the issue, closing.
